language: emacs-lisp
sudo: false
before_install:
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install $EVM_EMACS --use
env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-git-snapshot-travis
script:
  - emacs --version
  - make monky.elc
